

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend
        # image: #{IMAGE_NAME}#
        image: acrmar12.azurecr.io/backend:1295
      
...

apiVersion: v1
kind: Service 
metadata:
  name: backend-lb
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: backend1
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
...

apiVersion: v1
kind: Service
metadata:
  name: mybackendprivate-service
spec:
  selector:
    app: backend1
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None  # Headless service
