

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend
        # image: #{IMAGE_NAME}#
        image: acrmar07.azurecr.io/mybackend:1224
      
...

