apiVersion: v1
kind: Service 
metadata:
  name: nginx-lb
spec:
#   type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: nginxd2s
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
