apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql1
  template:
    metadata:
      labels:
        app: mysql1
    spec:
      containers:
        - name: mysql
          image: mysql # MySQL 5.7 image (or any other version)
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"  # Hardcoded MySQL root password
            - name: MYSQL_DATABASE
              value: "userdb"  # Database name to create on MySQL startup
            - name: MYSQL_USER
              value: "mysqluser"  # Username for non-root access
            - name: MYSQL_PASSWORD
              value: "mysqlpassword"  # Password for the non-root user
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service

metadata:
  name: mysql-service
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

      apiVersion: v1

 
