apiVersion: v1
kind: Service 
metadata:
  name: frontend-lb
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: myfrontendpod
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
