
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
      - name: devopspod
        # image: #{IMAGE_NAME}#
        image: acrmar06.azurecr.io/myapp:1171
      
        
        
