
trigger: none
pr: none



pool:
  vmImage: ubuntu-latest



parameters:

 - name: akscluster
   type: string
   default: aksmar16
 - name: tag
   type: string
   default: latest


 - name: tier
   type: string
   default: 'frontend'
   values: 
     - frontend
     - backend


  

variables:
  imageName-frontend: 'frontend'  # Your image name
  imageName-backend: 'backend'
  acrName: acrmar16


  dockerFilePath-frontend: frontend/Dockerfile
  dockerFilePath-backend: backend/Dockerfile
  IMAGE_NAME_frontend : $(acrName).azurecr.io/$(imageName-frontend):${{ parameters.tag }}
  IMAGE_NAME_backend : $(acrName).azurecr.io/$(imageName-backend):${{ parameters.tag }}
  akscluster: aksmar16
  aksrg: 'rg-mylabmylabuksouthp-example'
  manifests: '$(Build.SourcesDirectory)/abcno/${{ parameters.tier }}.yml'

jobs: 

  - job: aksjobfrontend_onlyaks
    displayName: AKSJobfrontend-onlyaks
    timeoutInMinutes: 3 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
    condition:   ${{ eq(parameters.tier, 'frontend' ) }}
    

    steps:
      - task: KubeloginInstaller@0
        inputs:
          kubeloginVersion: 'latest'
        displayName: installkubelogin
      - script: |
              sed -i "s|#{IMAGE_NAME}#|$(IMAGE_NAME_frontend)|g" $(manifests)
        displayName: 'Replace Image Name in Manifest'
        

      - task: KubernetesManifest@1
        displayName: DeployAKSPOD
        inputs:
          action: 'deploy'
          connectionType: 'azureResourceManager'
          azureSubscriptionConnection: 'myaksfeb072025'
          azureResourceGroup: '$(aksrg)'
          kubernetesCluster: '${{ parameters.akscluster }}'
          namespace: '${{ parameters.tier }}'
          manifests: '$(manifests)'
        
  - job: aksjobbackend_onlyaks
    displayName: AKSjobbackend-onlyaks
    timeoutInMinutes: 3 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
    condition:  ${{ eq(parameters.tier, 'backend' ) }}
    

    steps:
      - task: KubeloginInstaller@0
        inputs:
          kubeloginVersion: 'latest'
        displayName: installkubelogin
      - script: |
              sed -i "s|#{IMAGE_NAME}#|$(IMAGE_NAME_backend)|g" {{ parameters.tier }}.yml
        displayName: 'Replace Image Name in Manifest'
      - task: KubernetesManifest@1
        displayName: DeployAKSPOD
        inputs:
          action: 'deploy'
          connectionType: 'azureResourceManager'
          azureSubscriptionConnection: 'myaksfeb072025'
          azureResourceGroup: '$(aksrg)'
          kubernetesCluster: '${{ parameters.akscluster }}'
          namespace: ${{ parameters.tier }}
          manifests: '$(manifests)'
