apiVersion: v1
kind: Service 
metadata:
  name: backendexpose
spec:
#   type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: backend1
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
