apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
      - name: devopspod
        image: #{IMAGE_NAME}#
        # image: acrmar12.azurecr.io/frontend:1309
...

apiVersion: v1
kind: Service 
metadata:
  name: frontend-lb
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: frontend1
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
